- name: Create /etc/elasticsearch/certs/
  # IF ONLY RUNNING A SINGLE NODE
  #delegate_to: "{{ elastic_testnode }}"
  #run_once: true
  file:
    path: "/etc/elasticsearch/certs/"
    state: directory
    owner: root
    group: elasticsearch
    mode: 0750
  when:
    ansible_facts['distribution'] == "Ubuntu"

#- name: Copy Truststore to Remote
#  # IF ONLY RUNNING A SINGLE NODE
#  delegate_to: "{{ elastic_testnode }}"
#  run_once: true
#  copy:
#    src: "tls/certs/truststore.jks"
#    dest: "/etc/elasticsearch/certs/"
#    owner: root
#    group: elasticsearch
#    mode: 0750
#  when:
#    ansible_facts['distribution'] == "Ubuntu"

- name: Copy CA Chain to Remote
  # IF ONLY RUNNING A SINGLE NODE
  #delegate_to: "{{ elastic_testnode }}"
  #run_once: true
  copy:
    # using variables if desired, and other formats
    #src: "tls/certs/{{ hostvars[inventory_hostname].hostname }}.keystore.jks"
    #src: "tls/certs/{{ hostvars[inventory_hostname].hostname }}.flex.pkcs12"
    src: "tls/certs/ca-chain.cert.pem"
    dest: "/etc/elasticsearch/certs/"
    owner: root
    group: elasticsearch
    mode: 0750
  when:
    ansible_facts['distribution'] == "Ubuntu"

- name: Copy Elasticsearch Keystore to Remote
  # IF ONLY RUNNING A SINGLE NODE
  #delegate_to: "{{ elastic_testnode }}"
  #run_once: true
  copy:
    #src: "tls/certs/{{ hostvars[inventory_hostname].hostname }}.keystore.jks"
    src: "tls/certs/{{ hostvars[inventory_hostname].hostname }}.flex.pkcs12"
    dest: "/etc/elasticsearch/certs/"
    owner: root
    group: elasticsearch
    mode: 0750
  when:
    ansible_facts['distribution'] == "Ubuntu"

- name: Add Elasticsearch Keystore HTTP SSL Value - xpack.security.http.ssl.keystore.secure_password
  # IF ONLY RUNNING A SINGLE NODE
  #delegate_to: "{{ elastic_testnode }}"
  #run_once: true
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.keystore.secure_password -f
    responses:
      (?i)password: "{{ keystore_password }}"
  when:
    ansible_facts['distribution'] == "Ubuntu"

#- name: Add Elasticsearch Keystore Value - xpack.security.http.ssl.truststore.secure_password
#  # IF ONLY RUNNING A SINGLE NODE
#  delegate_to: "{{ elastic_testnode }}"
#  run_once: true
#  expect:
#    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.http.ssl.truststore.secure_password -f
#    responses:
#      (?i)password: "{{ truststore_password }}"
#  when:
#    ansible_facts['distribution'] == "Ubuntu"

- name: Add Elasticsearch Keystore Transport SSL Value - xpack.security.transport.ssl.keystore.secure_password
  # IF ONLY RUNNING A SINGLE NODE
  #delegate_to: "{{ elastic_testnode }}"
  #run_once: true
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.keystore.secure_password -f
    responses:
      (?i)password: "{{ keystore_password }}"
  when:
    ansible_facts['distribution'] == "Ubuntu"

#- name: Add Elasticsearch Keystore Value - xpack.security.transport.ssl.truststore.secure_password
#  # IF ONLY RUNNING A SINGLE NODE
#  delegate_to: "{{ elastic_testnode }}"
#  run_once: true
#  expect:
#    command: /usr/share/elasticsearch/bin/elasticsearch-keystore add xpack.security.transport.ssl.truststore.secure_password -f
#    responses:
#      (?i)password: "{{ truststore_password }}"
#  when:
#    ansible_facts['distribution'] == "Ubuntu"
