- name: Reset Password for User elastic
  delegate_to: "{{ elastic_testnode }}"
  run_once: true
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u elastic -i --url "https://{{ elastic_testnode }}:9200" -f
    responses:
      (?i)Please confirm: y
      (?i)Enter password: "{{ elastic_user_password }}"
      (?i)Re-enter password: "{{ elastic_user_password }}"
  when:
    ansible_facts['distribution'] == "Ubuntu"

- name: Reset Password for User kibana_system
  delegate_to: "{{ elastic_testnode }}"
  run_once: true
  expect:
    command: /usr/share/elasticsearch/bin/elasticsearch-reset-password -u kibana_system -i --url "https://{{ elastic_testnode }}:9200"
    responses:
      (?i)Please confirm: y
      (?i)Enter password: "{{ kibana_system_user_password }}"
      (?i)Re-enter password: "{{ kibana_system_user_password }}"
  when:
    ansible_facts['distribution'] == "Ubuntu"
