# Add Elasticsearch Repository

# Apt
# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-with-debian-package#deb-repo
- name: Import Apt Signing Key from URL, If Fingerprint Not Present
  ansible.builtin.apt_key:
    id: "{{ gpg.fingerprint }}"
    url: "{{ gpg.url }}"
    state: present
    keyring: /usr/share/keyrings/elasticsearch-keyring.gpg
  when:
    ansible_facts['pkg_mgr'] == "apt"

- name: Add Elastic Apt Repository
  delegate_to: localhost
  run_once: true
  blockinfile:
    #path: /etc/apt/sources.list.d/elastic-8.x.list
    path: /etc/apt/sources.list.d/elastic-9.x.list
    create: yes
    state: present
    #marker: ""
    #block: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
    block: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/9.x/apt stable main"
  when: ansible_facts['distribution'] == "Ubuntu"

- name: Update Apt Cache
  ansible.builtin.apt:
    update_cache: yes
  when:
    ansible_facts['pkg_mgr'] == "apt"

# RPM
# https://www.elastic.co/docs/deploy-manage/deploy/self-managed/install-elasticsearch-with-rpm
- name: Add Elastic RPM Repository
  delegate_to: localhost
  run_once: true
  blockinfile:
    path: /etc/yum.repos.d/elasticsearch.repo
    create: yes
    state: present
    #marker: ""
    # change 9 to 8 for those versions
    block: |
      [elasticsearch]
      name=Elasticsearch repository for 9.x packages
      baseurl=https://artifacts.elastic.co/packages/9.x/yum
      gpgcheck=1
      gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
      enabled=0
      autorefresh=1
      type=rpm-md
  when: ansible_facts['distribution'] == "RedHat" or ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "CentOS"
